#!/bin/bash
echo "============================================================"
echo "  Hyperbolic CORS Verification — api.hyperbolic.xyz"
echo "============================================================"
echo ""
echo "[1] Arbitrary Origin:"
curl -sI -H "Origin: https://evil.com" https://api.hyperbolic.xyz/v1/models | grep -i "access-control"
echo ""
echo "[2] Null Origin:"
curl -sI -H "Origin: null" https://api.hyperbolic.xyz/v1/models | grep -i "access-control"
echo ""
echo "[3] Credentials:"
curl -sI -H "Origin: https://evil.com" https://api.hyperbolic.xyz/v1/models | grep -i "credentials"
echo ""
echo "============================================================"
