#!/bin/bash
echo "============================================================"
echo "  DeepInfra CORS Verification — api.deepinfra.com"
echo "============================================================"
echo ""
echo "[1] Arbitrary Origin Reflection:"
curl -sI -H "Origin: https://evil.com" https://api.deepinfra.com/v1/openai/models | grep -i "access-control"
echo ""
echo "[2] Null Origin Bypass:"
curl -sI -H "Origin: null" https://api.deepinfra.com/v1/openai/models | grep -i "access-control"
echo ""
echo "[3] Credentials:"
curl -sI -H "Origin: https://evil.com" https://api.deepinfra.com/v1/openai/models | grep -i "credentials"
echo ""
echo "============================================================"
