#!/bin/bash
echo "============================================================"
echo "  🔴 MiniMax CORS + WeChat Pay Verification"
echo "============================================================"
echo ""
echo "[1] Origin + WeChat Pay Headers:"
curl -sI -H "Origin: https://evil.com" -X OPTIONS -H "Access-Control-Request-Headers: authorization" https://api.minimaxi.chat/v1/chat/completions | grep -i "access-control\|wechatpay\|token\|alb_"
echo ""
echo "[2] Null Origin:"
curl -sI -H "Origin: null" https://api.minimaxi.chat/v1/chat/completions | grep -i "access-control"
echo ""
echo "[3] DELETE Method:"
curl -sI -H "Origin: https://evil.com" -X OPTIONS -H "Access-Control-Request-Method: DELETE" https://api.minimaxi.chat/v1/chat/completions | grep -i "allow-methods"
echo ""
echo "============================================================"
