#!/bin/bash
echo "============================================================"
echo "  DeepSeek CORS Verification — api.deepseek.com"
echo "============================================================"
echo ""
echo "[1] Arbitrary Origin Reflection:"
curl -sI -H "Origin: https://evil.com" https://api.deepseek.com/v1/models | grep -i "access-control"
echo ""
echo "[2] Null Origin Bypass:"
curl -sI -H "Origin: null" https://api.deepseek.com/v1/models | grep -i "access-control"
echo ""
echo "[3] Credentials:"
curl -sI -H "Origin: https://evil.com" https://api.deepseek.com/v1/models | grep -i "credentials"
echo ""
echo "============================================================"
